const state={flow:null,object:'',project:'',queries:[],records:[],sample:[],judgments:{},benchmark:[],recovery:[],dedup:[],events:[],step:0};
const $=id=>document.getElementById(id), now=()=>new Date().toISOString();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>(s||'').toString().toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const doiNorm=s=>(s||'').toString().toLowerCase().replace(/^https?:\/\/(dx\.)?doi\.org\//,'').replace(/^doi:\s*/,'').trim();
function event(type,data={}){state.events.push({time:now(),type,...data})}
function parseCSV(text){let rows=[],row=[],cell='',q=false;for(let i=0;i<text.length;i++){let c=text[i],n=text[i+1];if(q){if(c==='"'&&n==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else{if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}}if(cell||row.length){row.push(cell);rows.push(row)}if(!rows.length)return[];let h=rows.shift().map(x=>x.trim());return rows.filter(r=>r.some(x=>x.trim())).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??''])))}
function pick(o,names){for(const n of names)if(o[n]!=null&&o[n]!=='')return o[n];let keys=Object.keys(o);for(const n of names){let k=keys.find(k=>norm(k)===norm(n));if(k)return o[k]}return''}
function canonical(o,source,qid=''){return{id:crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2),title:pick(o,['title','article_title','name']),doi:doiNorm(pick(o,['doi','DOI'])),year:String(pick(o,['year','publication_year','published'])||'').match(/\d{4}/)?.[0]||'',first_author:pick(o,['first_author','author','authors']).split(/[;,|]/)[0].trim(),source,query_id:qid||pick(o,['query_id','query','search_id']),raw:o}}
async function fileText(input){return input.files[0]?await input.files[0].text():''}
const flowSteps={queries:['home','object','search','relevance','benchmark','results'],benchmark:['home','object','search','benchmark','results'],compare:['home','object','search','relevance','benchmark','results'],full:['home','object','search','relevance','benchmark','results']};
const labels={home:'Case',object:'Object',search:'Search',relevance:'Relevance',benchmark:'Known literature',results:'Result'};
function currentSteps(){return flowSteps[state.flow]||['home']}
function show(name){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('s-'+name).classList.add('active');state.step=currentSteps().indexOf(name);renderProgress();if(name==='relevance'){$('objectEcho').textContent=state.object;makeSample()}if(name==='results')calculateResults()}
function renderProgress(){let steps=currentSteps();$('progress').innerHTML=steps.map((s,i)=>`<span class="stepdot ${i===state.step?'active':i<state.step?'done':''}">${i+1}. ${labels[s]}</span>`).join('')}
function next(){let s=currentSteps(),i=state.step;if(i<s.length-1)show(s[i+1])}function back(){let s=currentSteps(),i=state.step;if(i>0)show(s[i-1])}
document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{state.flow=b.dataset.flow;event('flow_selected',{flow:state.flow});renderQueries(state.flow==='compare'?2:1);show('object')});
document.querySelectorAll('.back').forEach(b=>b.onclick=back);document.querySelectorAll('.next').forEach(b=>b.onclick=()=>{if(currentSteps()[state.step]==='object'){state.object=$('object').value.trim();state.project=$('projectName').value.trim();if(!state.object){alert('Describe what you are trying to find before continuing.');return}event('object_defined',{object:state.object,project:state.project})}next()});
function renderQueries(n=1){$('queries').innerHTML='';for(let i=0;i<n;i++)addQueryRow()}
function addQueryRow(v=''){let i=$('queries').children.length+1,d=document.createElement('div');d.className='query-chip';d.innerHTML=`<input class="qinput" data-id="Q${String(i).padStart(3,'0')}" placeholder="Search query ${i}" value="${esc(v)}"><button class="secondary" title="Remove">×</button>`;d.querySelector('button').onclick=()=>d.remove();$('queries').appendChild(d)}
$('addQuery').onclick=()=>addQueryRow();$('db').onchange=()=>$('importBox').classList.toggle('hidden',$('db').value!=='import');
async function runOne(q,qid,db,limit){if(db==='openalex'){let j=await(await fetch(`https://api.openalex.org/works?search=${encodeURIComponent(q)}&per-page=${limit}`)).json();return(j.results||[]).map(x=>({id:crypto.randomUUID(),title:x.display_name||'',doi:doiNorm(x.doi||''),year:x.publication_year||'',first_author:x.authorships?.[0]?.author?.display_name||'',source:'OpenAlex',query_id:qid,raw:x}))}if(db==='crossref'){let j=await(await fetch(`https://api.crossref.org/works?query.bibliographic=${encodeURIComponent(q)}&rows=${limit}`)).json();return(j.message?.items||[]).map(x=>({id:crypto.randomUUID(),title:x.title?.[0]||'',doi:doiNorm(x.DOI||''),year:x.published?.['date-parts']?.[0]?.[0]||'',first_author:[x.author?.[0]?.family,x.author?.[0]?.given].filter(Boolean).join(', '),source:'Crossref',query_id:qid,raw:x}))}let j=await(await fetch(`https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=${encodeURIComponent(q)}&format=json&pageSize=${limit}`)).json();return(j.resultList?.result||[]).map(x=>({id:crypto.randomUUID(),title:x.title||'',doi:doiNorm(x.doi||''),year:x.pubYear||'',first_author:(x.authorString||'').split(',')[0],source:'Europe PMC',query_id:qid,raw:x}))}
$('runSearch').onclick=async()=>{let inputs=[...document.querySelectorAll('.qinput')],qs=inputs.map(x=>({id:x.dataset.id,text:x.value.trim()})).filter(x=>x.text);if(!qs.length&&$('db').value!=='import'){alert('Enter at least one query.');return}state.queries=qs;state.records=[];state.sample=[];state.judgments={};let db=$('db').value,limit=Math.min(200,Math.max(1,+$('limit').value||50));$('runStatus').textContent='Loading results…';try{if(db==='import'){let text=await fileText($('resultsFile'));if(!text)throw Error('Choose a results CSV first.');let src=$('importSource').value.trim()||'Imported database';state.records=parseCSV(text).map(o=>canonical(o,src));if(!state.queries.length){let ids=[...new Set(state.records.map(r=>r.query_id).filter(Boolean))];state.queries=ids.length?ids.map(id=>({id,text:id})): [{id:'Q001',text:'Imported search'}]}}else{for(const q of qs){let rs=await runOne(q.text,q.id,db,limit);state.records.push(...rs)}}event('results_loaded',{database:db,queries:state.queries,count:state.records.length});$('runStatus').textContent=`Loaded ${state.records.length} result occurrences across ${state.queries.length} search${state.queries.length===1?'':'es'}.`;$('toRelevance').disabled=false}catch(e){event('search_failed',{message:e.message});$('runStatus').textContent='Could not load results: '+e.message}}
function seeded(seed){let h=2166136261;for(let c of String(seed))h=Math.imul(h^c.charCodeAt(0),16777619);return()=>{h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function makeSample(){if(!state.records.length)return;let n=Math.min(state.records.length,Math.max(1,+$('sampleSize').value||20)),rand=seeded($('seed').value),arr=state.records.map((r,i)=>({r,k:rand()+i*1e-12})).sort((a,b)=>a.k-b.k).slice(0,n).map(x=>x.r);state.sample=arr;event('sample_created',{size:n,seed:$('seed').value});renderSample()}
$('makeSample').onclick=makeSample;
function renderSample(){$('sample').innerHTML=state.sample.map((r,i)=>`<div class="result-card"><div class="result-title">${i+1}. ${esc(r.title||'[Untitled record]')}</div><div class="meta">${esc(r.first_author)} ${r.year?'· '+esc(r.year):''} ${r.doi?'· DOI '+esc(r.doi):''}<br>${esc(r.source)} · ${esc(r.query_id||'')}</div><div class="judges"><button class="judge ${state.judgments[r.id]==='relevant'?'selected':''}" data-id="${r.id}" data-v="relevant">Relevant</button><button class="judge ${state.judgments[r.id]==='potential'?'selected':''}" data-id="${r.id}" data-v="potential">Potentially relevant</button><button class="judge ${state.judgments[r.id]==='irrelevant'?'selected':''}" data-id="${r.id}" data-v="irrelevant">Irrelevant</button></div></div>`).join('');document.querySelectorAll('.judge').forEach(b=>b.onclick=()=>{state.judgments[b.dataset.id]=b.dataset.v;event('relevance_judgment',{record_id:b.dataset.id,value:b.dataset.v});renderSample();renderRelSummary()});renderRelSummary()}
function renderRelSummary(){let vals=state.sample.map(r=>state.judgments[r.id]).filter(Boolean),rel=vals.filter(x=>x==='relevant').length,pot=vals.filter(x=>x==='potential').length,irr=vals.filter(x=>x==='irrelevant').length;$('relSummary').innerHTML=vals.length?`<div class="status"><b>${vals.length}/${state.sample.length} coded.</b> Relevant: ${rel} · Potentially relevant: ${pot} · Irrelevant: ${irr}</div>`:''}
$('toRelevance').onclick=()=>{if(state.flow==='benchmark')show('benchmark');else show('relevance')};
$('toBenchmark').onclick=()=>show('benchmark');
$('skipBench').onclick=()=>{state.benchmark=[];event('benchmark_skipped');show('results')};
$('loadBench').onclick=async()=>{let text=(await fileText($('benchFile')))||$('benchText').value;if(!text.trim()){$('benchStatus').textContent='Add benchmark CSV first.';return}state.benchmark=parseCSV(text).map(x=>canonical(x,'benchmark'));event('benchmark_loaded',{count:state.benchmark.length});$('benchStatus').textContent=`Loaded ${state.benchmark.length} known-relevant records.`};
$('benchContinue').onclick=()=>show('results');
function dedup(records){let out=[],doiMap=new Map(),bibMap=new Map();for(const r of records){let dk=doiNorm(r.doi),bk=[norm(r.title),r.year,norm(r.first_author)].join('|');let idx=dk&&doiMap.has(dk)?doiMap.get(dk):(!dk&&bibMap.has(bk)?bibMap.get(bk):null);if(idx!=null){let x=out[idx];x.sources=[...new Set([...x.sources,r.source])];x.query_ids=[...new Set([...x.query_ids,r.query_id].filter(Boolean))]}else{let x={...r,sources:[r.source],query_ids:[r.query_id].filter(Boolean)};delete x.raw;let i=out.push(x)-1;if(dk)doiMap.set(dk,i);else if(norm(r.title))bibMap.set(bk,i)}}return out}
function isMatch(b,r){if(b.doi&&r.doi)return doiNorm(b.doi)===doiNorm(r.doi);if(!b.title||!r.title)return false;return norm(b.title)===norm(r.title)&&(!b.year||!r.year||b.year===r.year)&&(!b.first_author||!r.first_author||norm(b.first_author)===norm(r.first_author))}
function statsFor(qid){let sample=state.sample.filter(r=>r.query_id===qid),vals=sample.map(r=>state.judgments[r.id]).filter(Boolean);return{retrieved:state.records.filter(r=>r.query_id===qid).length,coded:vals.length,rel:vals.filter(x=>x==='relevant').length,pot:vals.filter(x=>x==='potential').length,irr:vals.filter(x=>x==='irrelevant').length}}
function calculateResults(){state.dedup=dedup(state.records);state.recovery=state.benchmark.map(b=>{let r=state.dedup.find(x=>isMatch(b,x));return{benchmark:b,recovered:!!r,match:r||null}});let vals=state.sample.map(r=>state.judgments[r.id]).filter(Boolean),rel=vals.filter(x=>x==='relevant').length,pot=vals.filter(x=>x==='potential').length,strict=vals.length?rel/vals.length:null,broad=vals.length?(rel+pot)/vals.length:null,rec=state.recovery.filter(x=>x.recovered).length,total=state.benchmark.length;$('mRetrieved').textContent=state.records.length;$('mStrict').textContent=strict==null?'—':(100*strict).toFixed(1)+'%';$('mBroad').textContent=broad==null?'—':(100*broad).toFixed(1)+'%';$('mBench').textContent=total?`${rec}/${total}`:'—';let txt=[];if(strict!=null)txt.push(`In the coded sample, ${(100*strict).toFixed(1)}% of results were judged strictly relevant and ${(100*broad).toFixed(1)}% were relevant or potentially relevant.`);if(total)txt.push(`${rec} of ${total} known-relevant benchmark records were recovered.`);if(!txt.length)txt.push('No relevance sample or benchmark was completed; the export still records the search and retrieved corpus.');$('interpretation').innerHTML=`<b>What this check found</b><br>${esc(txt.join(' '))}`;$('querySummary').innerHTML=state.queries.map(q=>{let s=statsFor(q.id),p=s.coded?100*s.rel/s.coded:null;return`<tr><td><b>${esc(q.id)}</b><br>${esc(q.text)}</td><td>${s.retrieved}</td><td>${s.coded}</td><td>${s.rel}</td><td>${s.pot}</td><td>${s.irr}</td><td>${p==null?'—':p.toFixed(1)+'%'}</td></tr>`}).join('');$('benchSection').classList.toggle('hidden',!total);$('benchRows').innerHTML=state.recovery.map(x=>`<tr><td>${esc(x.benchmark.title)}</td><td class="${x.recovered?'ok':'bad'}">${x.recovered?'Yes':'No'}</td><td>${esc(x.match?.title||'')}</td><td>${esc(x.match?.sources?.join('; ')||'')}</td></tr>`).join('');event('results_calculated',{retrieved:state.records.length,deduplicated:state.dedup.length,strict_relevance:strict,broad_relevance:broad,benchmark_total:total,benchmark_recovered:rec})}
function dl(name,text,type='text/plain'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function csvEscape(v){v=String(v??'');return/[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}
$('downloadJson').onclick=()=>dl('search-check-audit.json',JSON.stringify({...state,exported_at:now(),version:'0.2.0a1-static'},null,2),'application/json');
$('downloadCsv').onclick=()=>{let h=['title','doi','year','first_author','sources','query_ids'];let rows=state.dedup.map(r=>[r.title,r.doi,r.year,r.first_author,r.sources.join('; '),r.query_ids.join('; ')]);dl('search-check-deduplicated.csv',[h,...rows].map(r=>r.map(csvEscape).join(',')).join('\n'),'text/csv')};
$('downloadReport').onclick=()=>{let vals=state.sample.map(r=>state.judgments[r.id]).filter(Boolean),rel=vals.filter(x=>x==='relevant').length,pot=vals.filter(x=>x==='potential').length,strict=vals.length?(100*rel/vals.length).toFixed(1)+'%':'N/A',broad=vals.length?(100*(rel+pot)/vals.length).toFixed(1)+'%':'N/A',rec=state.recovery.filter(x=>x.recovered).length;let html=`<!doctype html><meta charset="utf-8"><title>Search Check report</title><style>body{font-family:system-ui;max-width:900px;margin:40px auto;padding:0 20px;line-height:1.5}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ddd;padding:7px;text-align:left}</style><h1>Search Check report</h1><p><b>Object of search:</b> ${esc(state.object)}</p><p><b>Project:</b> ${esc(state.project||'—')}</p><h2>Queries</h2><ul>${state.queries.map(q=>`<li><b>${esc(q.id)}</b>: ${esc(q.text)}</li>`).join('')}</ul><h2>Summary</h2><p>Retrieved result occurrences: ${state.records.length}<br>Deduplicated records: ${state.dedup.length}<br>Strict relevance in coded sample: ${strict}<br>Broad relevance in coded sample: ${broad}<br>Benchmark recovery: ${state.benchmark.length?rec+'/'+state.benchmark.length:'Not assessed'}</p><h2>Researcher relevance judgments</h2><table><tr><th>Title</th><th>Query</th><th>Judgment</th></tr>${state.sample.map(r=>`<tr><td>${esc(r.title)}</td><td>${esc(r.query_id)}</td><td>${esc(state.judgments[r.id]||'Not coded')}</td></tr>`).join('')}</table><h2>Method note</h2><p>Relevance judgments are researcher-coded relative to the recorded object of search. Strict relevance is the proportion coded Relevant; broad relevance is the proportion coded Relevant or Potentially relevant. Benchmark recovery is reported separately and is not treated as the same construct as relevance.</p>`;dl('search-check-report.html',html,'text/html')};
$('restart').onclick=()=>location.reload();renderProgress();
